services:
  api:
    build: .
    container_name: nestjs_app
    restart: always
    environment:
      DATABASE_HOST: 18.220.91.129
      DATABASE_PORT: 5432
      DATABASE_USER: nest
      DATABASE_PASSWORD: nest
      DATABASE_NAME: nest_db
      JWT_SECRET: segredo_super_forte
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
